{% set name = "openff-fragmenter" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 33bb85f965dd22f9023fb76dd6518527e61f25b35b7b7560a0d88d52594989e5

build:
  number: 0

outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9
        - pip
        - rdkit
      run:
        - python >=3.9
        - openff-toolkit-base >=0.11.0
        - numpy
        - pydantic <3.0.0a0
        - networkx
        - jinja2
        - typing-extensions

    test:
      imports:
        - openff.fragmenter
        
  - name: {{ name|lower }}
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9
      run:
        - python >=3.9
        - rdkit
        - ambertools
        - {{ pin_subpackage('openff-fragmenter-base', exact=True) }}
    
    test:
      imports:
        - openff.fragmenter

about:
  home: https://github.com/openforcefield/openff-fragmenter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fragment molecules for quantum mechanics torsion scans.'
  description: |
    A package for fragmenting molecules for quantum mechanics torsion scans.
  doc_url: https://fragmenter.readthedocs.io/en/latest/
  dev_url: https://github.com/openforcefield/openff-fragmenter

extra:
  recipe-maintainers:
    - simonboothroyd
    - j-wags
    - mattwthompson
