{% set name = "openff-fragmenter" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 87bc1d7f713e9375e4773edae7e0678622dc88fa8c2a3e2bc0413c31dfcaaa61

build:
  number: 0

outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - openff-toolkit-base >=0.9.2
        - numpy
        - pydantic
        - networkx
        - jinja2
        - typing-extensions

    test:
      imports:
        - openff.fragmenter

  - name: {{ name|lower }}
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - rdkit
        - ambertools
        - {{ pin_subpackage('openff-fragmenter-base', exact=True) }}

    test:
      imports:
        - openff.fragmenter

about:
  home: https://github.com/openforcefield/openff-fragmenter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fragment molecules for quantum mechanics torsion scans.'
  description: |
    A package for fragmenting molecules for quantum mechanics torsion scans.
  doc_url: https://fragmenter.readthedocs.io/en/latest/
  dev_url: https://github.com/openforcefield/openff-fragmenter

extra:
  recipe-maintainers:
    - simonboothroyd
